'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useState, useTransition } from 'react'
import { findPracticeUsers, invitePracticeMember, publishPracticeChallenge, remindPracticeMember, revokePracticeMember, savePracticeFeedback, submitPracticeFlag } from '@/app/actions/practice'
import type { PracticeChallenge, PracticeRoomData } from '@/lib/practice/types'
import ChallengeEditor from './ChallengeEditor'

function ActionForm({ challengeId, kind, initial = '' }: { challengeId: string; kind: 'flag' | 'feedback'; initial?: string }) {
  const router = useRouter()
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState('')
  return <form className="mt-4 flex flex-col gap-2 sm:flex-row sm:flex-wrap" action={(data) => { setMessage(''); startTransition(async () => { try {
    const value = String(data.get(kind) || '')
    const result = kind === 'flag' ? await submitPracticeFlag(challengeId, value) : await savePracticeFeedback(challengeId, value)
    if ('error' in result) setMessage(result.error)
    else if (kind === 'flag') { setMessage(result.correct ? (result.alreadySolved ? 'Already solved.' : 'Correct flag.') : 'That flag is not correct yet.'); router.refresh() }
    else { setMessage('Feedback saved.'); router.refresh() }
  } catch { setMessage(kind === 'flag' ? 'Unable to submit the flag. Please try again.' : 'Unable to save feedback. Please try again.') } }) }}>
    {kind === 'feedback' ? <textarea aria-label="Challenge feedback" required maxLength={2000} name="feedback" defaultValue={initial} rows={2} className="input-field flex-1" placeholder="What worked, what was unclear, or what should change?" /> : <input aria-label="Challenge flag" required maxLength={500} name="flag" autoComplete="off" className="input-field flex-1 font-mono" placeholder="Enter flag" />}
    <button disabled={pending} className="btn-primary self-start disabled:opacity-50">{pending ? 'Sending…' : kind === 'flag' ? 'Submit flag' : 'Send feedback'}</button>
    {message && <p role="status" className="text-sm sm:basis-full" style={{ color: message.includes('Correct') || message.includes('saved') || message.includes('solved') ? '#22c55e' : 'var(--text-secondary)' }}>{message}</p>}
  </form>
}

function ChallengeCard({ challenge, data, onEdit }: { challenge: PracticeChallenge; data: PracticeRoomData; onEdit: () => void }) {
  const [publishPending, startPublish] = useTransition(); const [publishMessage, setPublishMessage] = useState('')
  const publication = data.publications.find((p) => p.practice_challenge_id === challenge.id)
  const [publishedId, setPublishedId] = useState(publication?.ctf_challenge_id)
  const solved = data.attempts.some((a) => a.challenge_id === challenge.id && a.user_id === data.userId && a.is_correct)
  const ownFeedback = data.feedback.find((f) => f.challenge_id === challenge.id && f.user_id === data.userId)?.message ?? ''
  const attempts = data.attempts.filter((a) => a.challenge_id === challenge.id)
  const feedback = data.feedback.filter((f) => f.challenge_id === challenge.id)
  return <article className="rounded-xl border p-5" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)' }}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold" style={{ color: 'var(--text-primary)' }}>{challenge.title}</h3>{solved && <span className="rounded-full bg-green-500/10 px-2 py-0.5 text-xs text-green-500">Solved</span>}{!challenge.is_active && <span className="rounded-full px-2 py-0.5 text-xs" style={{ backgroundColor: 'var(--input-bg)', color: 'var(--text-muted)' }}>Inactive</span>}</div><p className="mt-1 text-xs uppercase tracking-wide" style={{ color: 'var(--text-muted)' }}>{challenge.category} · {challenge.difficulty} · {challenge.points} practice points</p></div>{data.isAdmin && <button onClick={onEdit} className="rounded-lg px-3 py-2 text-sm" style={{ backgroundColor: 'var(--input-bg)', color: 'var(--text-secondary)' }}>Edit</button>}</div>
    <p className="mt-4 whitespace-pre-wrap" style={{ color: 'var(--text-secondary)' }}>{challenge.description}</p>
    <div className="mt-4 flex flex-wrap gap-3 text-sm">{challenge.learn_topic_slug && challenge.learn_lesson_slug && <Link className="text-[var(--accent)] underline" href={`/learn/${challenge.learn_topic_slug}/${challenge.learn_lesson_slug}`}>Open linked lesson</Link>}{challenge.upload_id && <a className="text-[var(--accent)] underline" href={`/api/practice/files/${challenge.upload_id}`}>Download attachment</a>}</div>
    {challenge.hint && <details className="mt-4"><summary className="cursor-pointer font-medium" style={{ color: 'var(--text-secondary)' }}>Hint</summary><p className="mt-2 whitespace-pre-wrap text-sm" style={{ color: 'var(--text-muted)' }}>{challenge.hint}</p></details>}
    {challenge.explanation && <details className="mt-3"><summary className="cursor-pointer font-medium" style={{ color: 'var(--text-secondary)' }}>Explanation</summary><p className="mt-2 whitespace-pre-wrap text-sm" style={{ color: 'var(--text-muted)' }}>{challenge.explanation}</p></details>}
    {challenge.is_active && <><ActionForm challengeId={challenge.id} kind="flag" /><ActionForm challengeId={challenge.id} kind="feedback" initial={ownFeedback} /></>}
    {data.isAdmin && <div className="mt-5 border-t pt-4" style={{ borderColor: 'var(--border-color)' }}><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="font-medium">Recent activity</h4><p className="text-xs" style={{ color: 'var(--text-muted)' }}>{attempts.length} attempts · {feedback.length} feedback entries</p></div>{publishedId ? <Link href={`/ctf/${publishedId}`} className="text-sm text-[var(--accent)] underline">View global copy</Link> : <button disabled={publishPending} onClick={() => startPublish(async () => { try { const result = await publishPracticeChallenge(challenge.id); if ('error' in result) setPublishMessage(result.error); else { setPublishedId(result.id); setPublishMessage('Published as a global snapshot. Later practice edits will not change it.') } } catch { setPublishMessage('Unable to publish the challenge. Please try again.') } })} className="btn-primary disabled:opacity-50">{publishPending ? 'Publishing…' : 'Publish global snapshot'}</button>}</div>{publishMessage && <p role="status" className="mt-2 text-sm" style={{ color: publishMessage.startsWith('Published') ? '#22c55e' : '#ef4444' }}>{publishMessage}</p>}{attempts.length > 0 && <ul aria-label="Recent attempts" className="mt-3 space-y-2">{attempts.map((a) => <li key={a.id} className="flex flex-wrap justify-between gap-2 rounded-lg p-3 text-sm" style={{ backgroundColor: 'var(--input-bg)' }}><span><span className="font-medium">{data.members.find(m => m.user_id === a.user_id)?.display_name ?? 'Tester'}</span> · <span className={a.is_correct ? 'text-green-500' : 'text-red-500'}>{a.is_correct ? 'Correct' : 'Incorrect'}</span></span><time style={{ color: 'var(--text-muted)' }}>{new Date(a.created_at).toLocaleString()}</time></li>)}</ul>}{feedback.length > 0 && <ul aria-label="Recent feedback" className="mt-3 space-y-2">{feedback.map((f) => <li key={`${f.challenge_id}-${f.user_id}`} className="rounded-lg p-3 text-sm" style={{ backgroundColor: 'var(--input-bg)' }}><span className="font-medium">{data.members.find(m => m.user_id === f.user_id)?.display_name ?? 'Tester'}:</span> {f.message}<time className="mt-1 block text-xs" style={{ color: 'var(--text-muted)' }}>{new Date(f.updated_at).toLocaleString()}</time></li>)}</ul>}</div>}
  </article>
}

export default function PracticeRoom({ data }: { data: PracticeRoomData }) {
  const router = useRouter()
  const [editing, setEditing] = useState<PracticeChallenge | null | 'new'>(null)
  const [query, setQuery] = useState(''); const [users, setUsers] = useState<Array<{ id: string; display_name: string }>>([]); const [memberMessage, setMemberMessage] = useState(''); const [pending, startTransition] = useTransition()
  const mutate = (fn: () => Promise<{ success: true } | { error: string }>, success: string) => startTransition(async () => { try { const result = await fn(); setMemberMessage('error' in result ? result.error : success); if (!('error' in result)) router.refresh() } catch { setMemberMessage('Unable to complete that action. Please try again.') } })
  return <div className="space-y-6">
    <Link href="/practice" className="text-sm text-[var(--accent)]">← All practice rooms</Link>
    <div><h1 className="text-3xl font-bold" style={{ color: 'var(--text-primary)' }}>{data.room.title}</h1><p className="mt-2" style={{ color: 'var(--text-secondary)' }}>{data.room.description}</p><p className="mt-3 text-sm font-medium text-amber-500">Practice points only — solves here do not affect XP, global scores, badges, teams, or first blood.</p></div>
    {data.isAdmin && <section className="rounded-xl border p-5" style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border-color)' }}><h2 className="font-semibold">Invite member</h2><p className="mt-1 text-sm" style={{ color: 'var(--text-muted)' }}>Invitations grant access immediately. Members cannot join themselves.</p><div className="mt-3 flex gap-2"><input aria-label="Search registered users" value={query} onChange={e => setQuery(e.target.value)} className="input-field flex-1" placeholder="Search registered users" /><button disabled={pending || query.trim().length < 2} className="btn-primary disabled:opacity-50" onClick={() => startTransition(async () => { try { const found = await findPracticeUsers(query); setUsers(found); setMemberMessage(found.length ? '' : 'No registered users found.') } catch { setUsers([]); setMemberMessage('Unable to search users. Please try again.') } })}>Search</button></div>{memberMessage && <p className="mt-2 text-sm" role="status">{memberMessage}</p>}{users.length > 0 && <ul className="mt-3 space-y-2">{users.map(u => <li key={u.id} className="flex items-center justify-between gap-2"><span>{u.display_name}</span><button disabled={pending} className="btn-primary disabled:opacity-50" onClick={() => mutate(() => invitePracticeMember(data.room.id, u.id), 'Member invited.')}>Invite</button></li>)}</ul>}
      <h3 className="mt-6 font-medium">Members</h3>{data.members.length === 0 ? <p className="mt-2 text-sm" style={{ color: 'var(--text-muted)' }}>No invited members yet.</p> : <ul className="mt-2 divide-y" style={{ borderColor: 'var(--border-color)' }}>{data.members.map(m => <li key={m.user_id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><span className="font-medium">{m.display_name}</span><p className="text-xs" style={{ color: 'var(--text-muted)' }}>Invited {new Date(m.invited_at).toLocaleDateString()}{m.last_reminded_at ? ` · reminded ${new Date(m.last_reminded_at).toLocaleDateString()}` : ''}</p></div><div className="flex gap-2"><button disabled={pending} onClick={() => mutate(() => remindPracticeMember(data.room.id, m.user_id), 'Reminder sent.')} className="rounded-lg px-3 py-2 text-sm" style={{ backgroundColor: 'var(--input-bg)' }}>Remind</button><button disabled={pending} onClick={() => mutate(() => revokePracticeMember(data.room.id, m.user_id), 'Access revoked.')} className="rounded-lg px-3 py-2 text-sm text-red-500" style={{ backgroundColor: 'var(--input-bg)' }}>Revoke</button></div></li>)}</ul>}</section>}
    {data.isAdmin && <div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Challenges</h2><p className="text-sm" style={{ color: 'var(--text-muted)' }}>Publishing creates a separate global snapshot. Later edits stay private.</p></div><button className="btn-primary" onClick={() => setEditing('new')}>Add challenge</button></div>}
    {editing && <ChallengeEditor key={editing === 'new' ? 'new' : editing.id} roomId={data.room.id} challenge={editing === 'new' ? undefined : editing} onCancel={() => setEditing(null)} onSaved={() => { setEditing(null); router.refresh() }} />}
    {data.challenges.length === 0 ? <div className="rounded-xl border py-12 text-center" style={{ borderColor: 'var(--border-color)', color: 'var(--text-muted)' }}>No challenges are available in this room yet.</div> : <div className="space-y-4">{data.challenges.map(c => <ChallengeCard key={c.id} challenge={c} data={data} onEdit={() => setEditing(c)} />)}</div>}
  </div>
}
